### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by daptordarattler**
At least a readme file, then others can update it with useful information

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi @daptordarattler 
I'm sorry, I just discover this repository, are you able to fix conflicts?
I clearly understand if you could not do it.

**Comment by matks** [comment]
This contribution is very valuable so I rebased it myself.

I would love a quick review of @kpodemski or @Matt75 as they are module experts.

**Comment by kpodemski** [comment]
@matks the same information is available in the developer documentation, not sure if we need it here

**Comment by matks** [comment]
@kpodemski You're right. We can add a simple link to devdocs.

**Comment by matks** [comment]
@kpodemski better ? 😄

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@matks awesome 👍

**Pull request merged**
